/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],
  sidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "introduction",
    },
    {
      type: "doc",
      label: "Methodology",
      id: "methodology",
    },
    {
      type: "doc",
      label: "Call For Data",
      id: "call_for_data",
    },
    {
      type: 'html',
      value: '<hr />',
    },
    {
      type: "doc",
      label: "A01 - Logic Bug",
      id: "A01_logic_bug",
    },
  ],
};

module.exports = sidebars;
