/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],
  sidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "introduction",
    },
    {
      type: "doc",
      label: "Methodology",
      id: "methodology",
    },
    {
      type: "doc",
      label: "Call For Data",
      id: "call_for_data",
    },
    {
      type: "html",
      value: "<hr />",
    },
    {
      type: "category",
      label: "A01 - Logic Bug",
      link: { type: "doc", id: "A01_logic_bug/index" },
      items: [
        "A01_logic_bug/example_1",
        {
          type: "link",
          label: "Patch it! (Coming Soon)",
          href: "#"
        }
      ],
    },
    {
      type: "category",
      label: "A02 - Account Validation",
      link: { type: "doc", id: "A02_account_validation/index" },
      items: [
        "A02_account_validation/missing_signer_check",
        "A02_account_validation/missing_ownership_check",
        "A02_account_validation/missing_program_validation",
        "A02_account_validation/account_confusion",
      ],
    },
  ],
};

module.exports = sidebars;
